### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by marbew** [gacallea/cardanoNodeBuilder#1]
Hi with 
root@01init:~/cardanoNodeBuilder# docker -v
Docker version 19.03.8, build afacb8b7f0
root@01init:~/cardanoNodeBuilder# docker-compose -v
docker-compose version 1.25.0, build unknown
root@01init:~/cardanoNodeBuilder# cat /etc/issue
Ubuntu 20.04 LTS \n \l
I receive this error: ERROR: Version in "./docker-compose.yml" is unsupported.

**Comment by marbew** [comment]
Fixed by changing version from 3.8 to 3.7 on a fresh 20.04 Ubuntu image.

**Comment by gacallea** [comment]
Hey, apologies for the late reply.

I'm glad you sorted it out. JFYI: your version of Docker is probably older than the one I use (latest), hence it doesn't support the latest version.
